apiVersion: apps/v1
kind: Deployment
metadata:
  name: howgerwatch
  namespace: aotter
  labels:
    app: howgerwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: howgerwatch
  template:
    metadata:
      labels:
        app: howgerwatch
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: howgerwatch
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
            limits:
              memory: "1Gi"
              cpu: "512m"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 2
            timeoutSeconds: 2